# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto_files import audio_service_pb2 as proto__files_dot_audio__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto_files/audio_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioGeneratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateAudio = channel.unary_unary(
                '/audio_service.AudioGenerator/GenerateAudio',
                request_serializer=proto__files_dot_audio__service__pb2.AudioRequest.SerializeToString,
                response_deserializer=proto__files_dot_audio__service__pb2.AudioResponse.FromString,
                _registered_method=True)


class AudioGeneratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateAudio(self, request, context):
        """Generate audio from text with emotions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAudio,
                    request_deserializer=proto__files_dot_audio__service__pb2.AudioRequest.FromString,
                    response_serializer=proto__files_dot_audio__service__pb2.AudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audio_service.AudioGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audio_service.AudioGenerator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioGenerator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio_service.AudioGenerator/GenerateAudio',
            proto__files_dot_audio__service__pb2.AudioRequest.SerializeToString,
            proto__files_dot_audio__service__pb2.AudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
