# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_files/audio_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto_files/audio_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto_files/audio_service.proto\x12\raudio_service\"<\n\x0c\x41udioRequest\x12,\n\x08segments\x18\x01 \x03(\x0b\x32\x1a.audio_service.TextEmotion\",\n\x0bTextEmotion\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x65motion\x18\x02 \x01(\t\"H\n\rAudioResponse\x12\x17\n\x0f\x61udio_file_path\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t2^\n\x0e\x41udioGenerator\x12L\n\rGenerateAudio\x12\x1b.audio_service.AudioRequest\x1a\x1c.audio_service.AudioResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.audio_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=50
  _globals['_AUDIOREQUEST']._serialized_end=110
  _globals['_TEXTEMOTION']._serialized_start=112
  _globals['_TEXTEMOTION']._serialized_end=156
  _globals['_AUDIORESPONSE']._serialized_start=158
  _globals['_AUDIORESPONSE']._serialized_end=230
  _globals['_AUDIOGENERATOR']._serialized_start=232
  _globals['_AUDIOGENERATOR']._serialized_end=326
# @@protoc_insertion_point(module_scope)
