# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_files/image_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto_files/image_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto_files/image_service.proto\x12\rimage_service\":\n\x0cImageRequest\x12*\n\x06scenes\x18\x01 \x03(\x0b\x32\x1a.image_service.ScenePrompt\"9\n\x0bScenePrompt\x12\x14\n\x0cscene_number\x18\x01 \x01(\x05\x12\x14\n\x0cimage_prompt\x18\x02 \x01(\t\"^\n\rImageResponse\x12-\n\x06images\x18\x01 \x03(\x0b\x32\x1d.image_service.GeneratedImage\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\":\n\x0eGeneratedImage\x12\x14\n\x0cscene_number\x18\x01 \x01(\x05\x12\x12\n\nimage_path\x18\x02 \x01(\t2_\n\x0eImageGenerator\x12M\n\x0eGenerateImages\x12\x1b.image_service.ImageRequest\x1a\x1c.image_service.ImageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.image_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=50
  _globals['_IMAGEREQUEST']._serialized_end=108
  _globals['_SCENEPROMPT']._serialized_start=110
  _globals['_SCENEPROMPT']._serialized_end=167
  _globals['_IMAGERESPONSE']._serialized_start=169
  _globals['_IMAGERESPONSE']._serialized_end=263
  _globals['_GENERATEDIMAGE']._serialized_start=265
  _globals['_GENERATEDIMAGE']._serialized_end=323
  _globals['_IMAGEGENERATOR']._serialized_start=325
  _globals['_IMAGEGENERATOR']._serialized_end=420
# @@protoc_insertion_point(module_scope)
