# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_files/story_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto_files/story_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto_files/story_service.proto\x12\rstory_service\"0\n\x0cStoryRequest\x12\x11\n\tstoryline\x18\x01 \x01(\t\x12\r\n\x05genre\x18\x02 \x01(\t\">\n\rStoryResponse\x12\r\n\x05story\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x1f\n\x0eProcessRequest\x12\r\n\x05story\x18\x01 \x01(\t\"d\n\x0fProcessResponse\x12\x31\n\tsentences\x18\x01 \x03(\x0b\x32\x1e.story_service.SentenceEmotion\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"0\n\x0fSentenceEmotion\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x65motion\x18\x02 \x01(\t\"\x1d\n\x0cSceneRequest\x12\r\n\x05story\x18\x01 \x01(\t\"[\n\rSceneResponse\x12*\n\x06scenes\x18\x01 \x03(\x0b\x32\x1a.story_service.ScenePrompt\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"_\n\x0bScenePrompt\x12\x14\n\x0cscene_number\x18\x01 \x01(\x05\x12\x12\n\nstart_line\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_line\x18\x03 \x01(\x05\x12\x14\n\x0cimage_prompt\x18\x04 \x01(\t2\x8c\x02\n\x0eStoryGenerator\x12L\n\rGenerateStory\x12\x1b.story_service.StoryRequest\x1a\x1c.story_service.StoryResponse\"\x00\x12W\n\x14ProcessStoryEmotions\x12\x1d.story_service.ProcessRequest\x1a\x1e.story_service.ProcessResponse\"\x00\x12S\n\x14GenerateScenePrompts\x12\x1b.story_service.SceneRequest\x1a\x1c.story_service.SceneResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.story_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STORYREQUEST']._serialized_start=50
  _globals['_STORYREQUEST']._serialized_end=98
  _globals['_STORYRESPONSE']._serialized_start=100
  _globals['_STORYRESPONSE']._serialized_end=162
  _globals['_PROCESSREQUEST']._serialized_start=164
  _globals['_PROCESSREQUEST']._serialized_end=195
  _globals['_PROCESSRESPONSE']._serialized_start=197
  _globals['_PROCESSRESPONSE']._serialized_end=297
  _globals['_SENTENCEEMOTION']._serialized_start=299
  _globals['_SENTENCEEMOTION']._serialized_end=347
  _globals['_SCENEREQUEST']._serialized_start=349
  _globals['_SCENEREQUEST']._serialized_end=378
  _globals['_SCENERESPONSE']._serialized_start=380
  _globals['_SCENERESPONSE']._serialized_end=471
  _globals['_SCENEPROMPT']._serialized_start=473
  _globals['_SCENEPROMPT']._serialized_end=568
  _globals['_STORYGENERATOR']._serialized_start=571
  _globals['_STORYGENERATOR']._serialized_end=839
# @@protoc_insertion_point(module_scope)
