# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto_files import story_service_pb2 as proto__files_dot_story__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto_files/story_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StoryGeneratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateStory = channel.unary_unary(
                '/story_service.StoryGenerator/GenerateStory',   #calls our function
                request_serializer=proto__files_dot_story__service__pb2.StoryRequest.SerializeToString,     #sends request
                response_deserializer=proto__files_dot_story__service__pb2.StoryResponse.FromString,        #receive respone from function
                _registered_method=True)
        self.ProcessStoryEmotions = channel.unary_unary(
                '/story_service.StoryGenerator/ProcessStoryEmotions',
                request_serializer=proto__files_dot_story__service__pb2.ProcessRequest.SerializeToString,
                response_deserializer=proto__files_dot_story__service__pb2.ProcessResponse.FromString,
                _registered_method=True)
        self.GenerateScenePrompts = channel.unary_unary(
                '/story_service.StoryGenerator/GenerateScenePrompts',
                request_serializer=proto__files_dot_story__service__pb2.SceneRequest.SerializeToString,
                response_deserializer=proto__files_dot_story__service__pb2.SceneResponse.FromString,
                _registered_method=True)


class StoryGeneratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateStory(self, request, context):
        """Generate a story based on storyline and genre
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessStoryEmotions(self, request, context):
        """Break a story into sentences with associated emotions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateScenePrompts(self, request, context):
        """Divide a story into scenes with image prompts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoryGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateStory': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateStory,
                    request_deserializer=proto__files_dot_story__service__pb2.StoryRequest.FromString,
                    response_serializer=proto__files_dot_story__service__pb2.StoryResponse.SerializeToString,
            ),
            'ProcessStoryEmotions': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessStoryEmotions,
                    request_deserializer=proto__files_dot_story__service__pb2.ProcessRequest.FromString,
                    response_serializer=proto__files_dot_story__service__pb2.ProcessResponse.SerializeToString,
            ),
            'GenerateScenePrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateScenePrompts,
                    request_deserializer=proto__files_dot_story__service__pb2.SceneRequest.FromString,
                    response_serializer=proto__files_dot_story__service__pb2.SceneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'story_service.StoryGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('story_service.StoryGenerator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StoryGenerator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateStory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/story_service.StoryGenerator/GenerateStory',
            proto__files_dot_story__service__pb2.StoryRequest.SerializeToString,
            proto__files_dot_story__service__pb2.StoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessStoryEmotions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/story_service.StoryGenerator/ProcessStoryEmotions',
            proto__files_dot_story__service__pb2.ProcessRequest.SerializeToString,
            proto__files_dot_story__service__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateScenePrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/story_service.StoryGenerator/GenerateScenePrompts',
            proto__files_dot_story__service__pb2.SceneRequest.SerializeToString,
            proto__files_dot_story__service__pb2.SceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
